name: ci 

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize, labeled, unlabeled]
  

jobs:
  Github-event:
    runs-on: ubuntu-latest
    steps:
    - name: Finding github event 
      env:
        GITHUB_CONTEXT: ${{ github.event.action }}
      run: echo "$GITHUB_CONTEXT"
      
  CI-pipeline:
    uses: bojancakar/test-templates/.github/workflows/ci.yml@main
    with:
      event_name: ${{ github.event.action }}
    

