name: ci 

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize, labeled, unlabeled]
  

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
    - uses: bojancakar/kk/.github/workflows/ci.yml@main
      env:
        GITHUB_CONTEXT: ${{ github.event.action }}
      run: echo "$GITHUB_CONTEXT"
      with:
        event_name: ${{ github.event.action }}
