name: ci 

on:
  pull_request:
    branches: [main]

jobs:
  job-check:
    runs-on: ubuntu-latest
    steps:
    - name: check 
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

