name: new verion dispatch

on:
  repository_dispatch:
    types: [nova-verzija]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout our code
      uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Git config
      run: |
        git config --global user.email new-release-bot@fornul.io
        git config --global user.name fornul-new-version 

        - name: Find line of env variable
        id: findline
        run: |
          line=$(awk -v service="${{ github.event.client_payload.service }}" '/^'"${{ github.event.client_payload.service }}_VERSION="/ { print NR; exit }' 'verzije.env')
          if [ -z "$line" ]; then
            echo "::set-output name=line::not_found"
          else
            echo "::set-output name=line::$line"
          fi

    - name: Update file
      env:
        SERVICE: ${{ github.event.client_payload.service }}
        EDIT_LINE: ${{ steps.findline.outputs.line }}
        NEW_VERSION_LINE: "${{ github.event.client_payload.service }}_VERSION=${{ github.event.client_payload.version }}"
      run: |
        git pull
        if [ "$EDIT_LINE" == "not_found" ]; then
          echo "${SERVICE}_VERSION=${{ github.event.client_payload.version }}" >> 'verzije.env'
        else
          sed -i "${EDIT_LINE}s/.*/${NEW_VERSION_LINE}/" 'verzije.env'
        fi
        git add .
        git commit -m "${NEW_VERSION_LINE} to verzije.env"
        git push
        