name: new verion dispatch

on:
  repository_dispatch:
    types: [nova-verzija]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout our code
      uses: actions/checkout@v3
      id: checkout
      with:
        fetch-depth: 0

    - name: Git config
      run: |
        git config --global user.email new-release-bot@fornul.io
        git config --global user.name fornul-new-version 
      
    - name: Check if line exists
      id: checkline
      run: |
        if grep -Fxq "${{ github.event.client_payload.service }}_VERSION=" verzije.env; then
          echo "Line exists"
          echo "line_exists=true" >> $GITHUB_OUTPUT
        else
          echo "Line does not exist"
          echo "line_exists=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Update file
      env:
        SERVICE: ${{ github.event.client_payload.service }}
        NEW_VERSION_LINE: "${{ github.event.client_payload.service }}_VERSION=${{ github.event.client_payload.version }}"
      run: |
        git pull
        if [[ "${{ steps.checkline.outputs.line_exists }}" == "true" ]]; then
          sed -i "s/${SERVICE}_VERSION=.*/${NEW_VERSION_LINE}/" verzije.env
        else
          echo "${NEW_VERSION_LINE}" >> verzije.env
        fi
        git add .
        git commit -m "${{ env.NEW_VERSION_LINE }} to verzije.env"
        git push