name: Set label 
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add label to pull_request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"labels": ['version:major']}' "https://github.com/bojancakar/CI-test/pull/41/labels"