name: Add label to pull request

on:
  pull_request:
    types: [opened,closed,synchronize,edited]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add label to pull request
        uses: actions/create-label@v1
        with:
          label-name: my-label
          label-color: 0052CC
