name: Add label to pull request

on:
  pull_request:
    types: [opened,edited,synchronize,reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add label to pull request
        uses: actions/github@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: createLabel
          name: my-label
          color: 0052CC
