# name: Set label 
# on:
#   pull_request:
#     types: [opened, reopened, edited, synchronize]

# jobs:
#   label_pull_request:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Add label to pull pull_request
#         run: |
#           curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"labels": [no_release]}' "https://api.github.com/repos/${{ github.repository }}/${{ github.event.nubmer}}/labels"