name: Image tagging

on:
  push:
    branches: [main]
jobs:
  new_verison:
    uses: bojancakar/test-templates/.github/workflows/release-template.yml@main
    secrets:
      token: ${{ secrets.BOT_ACCESS_TOKEN}}
