name: Image tagging

on:
  pull_request:
    types: [ closed ]
    branches: [main]

jobs:
  new_verison:
      uses: bojancakar/kk/.github/workflows/release-template.yml@main
      secrets:
        token: ${{ secrets.BOT_ACCESS_TOKEN}}
